(TeX-add-style-hook "YanWang-Dissertation"
 (lambda ()
    (LaTeX-add-bibliographies
     "Biblio-Database")
    (TeX-add-symbols
     "hsp")
    (TeX-run-style-hooks
     "listings"
     "titlesec"
     "cite"
     "color"
     "dvipsnames"
     "graphicx"
     "final"
     "eqlist"
     "amssymb"
     "amsmath"
     "microtype"
     "textcomp"
     "lmodern"
     ""
     "fontenc"
     "T1"
     "latex2e"
     "psuthesis12"
     "psuthesis"
     "12pt"
     "ms"
     "SupplementaryMaterial/UserDefinedCommands"
     "Chapter-1/Chapter-1"
     "Chapter-2/Chapter-2"
     "Chapter-3/Chapter-3"
     "Chapter-4/Chapter-4"
     "Chapter-5/Chapter-5"
     "Appendix-A/Appendix-A"
     "Appendix-B/Appendix-B"
     "Appendix-C/Appendix-C"
     "Appendix-D/Appendix-D")))

